spring.application.name=config-server
spring.profiles.active=native
#Telling the server to fetch all the configurations from the given path
spring.cloud.config.server.native.search-locations=classpath:/config
server.port=8888

