spring.application.name=api-gateway
server.port=8080
# API GATEWAY
# 1. USER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/user/**
# 2. CHAT-ROOM-SERVICE
spring.cloud.gateway.server.webflux.routes[1].id=chat-room-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://CHAT-ROOM-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/chat-room/**
# 3. MESSAGE-SERVICE
spring.cloud.gateway.server.webflux.routes[2].id=message-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://MESSAGE-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/message/**
# 4. MESSAGE-SERVICE
spring.cloud.gateway.server.webflux.routes[3].id=websocket-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://WEBSOCKET-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/chat/**
# Eureka client configuration
eureka.client.service-url.default-zone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${eureka.instance.hostname}:${spring.application.name}:${server.port}
