spring.application.name=api-gateway
server.port=8080
jwt.secretKey=eyJhbGciOiJIUzI1NiJ9eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTc1NTI3NDM0NywiaWF0IjoxNzU1Mjc0MzQ3fQBYhZFx5XUo0pINpD9xKBZjE8yHEJ7rtnNNVM6epYaM
# API GATEWAY

# 1. USER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/user/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=AuthenticationFilter

# 2. CHAT-ROOM-SERVICE
spring.cloud.gateway.server.webflux.routes[1].id=chat-room-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://CHAT-ROOM-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/chat-room/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=AuthenticationFilter

# 3. MESSAGE-SERVICE
spring.cloud.gateway.server.webflux.routes[2].id=message-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://MESSAGE-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/message/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=AuthenticationFilter

# 4. WEBSOCKET-SERVICE
spring.cloud.gateway.server.webflux.routes[3].id=websocket-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://WEBSOCKET-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/chat/**

# 5. AUTH-SERVICE (no authentication filter here)
spring.cloud.gateway.server.webflux.routes[4].id=auth-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/auth/**

# Eureka client configuration
eureka.client.service-url.default-zone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${eureka.instance.hostname}:${spring.application.name}:${server.port}
