spring.application.name=auth-service
server.port=8989
jwt.secretKey=eyJhbGciOiJIUzI1NiJ9eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTc1NTI3NDM0NywiaWF0IjoxNzU1Mjc0MzQ3fQBYhZFx5XUo0pINpD9xKBZjE8yHEJ7rtnNNVM6epYaM

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/Auth
spring.datasource.username=postgres
spring.datasource.password=63pratibha92
spring.jpa.hibernate.ddl-auto=update

frontend.url=http://localhost:5173

# Eureka client configuration
eureka.client.service-url.default-zone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${eureka.instance.hostname}:${spring.application.name}:${server.port}
