spring.application.name=chat-room-service
server.port=8082
spring.data.mongodb.uri=mongodb://localhost:27017/Chats
spring.data.mongodb.database=Chats
spring.devtools.restart.enabled=true
# Eureka client configuration
eureka.client.service-url.default-zone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${eureka.instance.hostname}:${spring.application.name}:${server.port}
