spring.application.name=websocket-service
server.port=8084
spring.devtools.restart.enabled=true
# Eureka client configuration
eureka.client.service-url.default-zone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${eureka.instance.hostname}:${spring.application.name}:${server.port}
#Rabbit-MQ
rabbitmq.host=localhost
rabbitmq.port=5672
rabbitmq.username=guest
rabbitmq.password=guest
# Exchange for publishing brand new messages from WebSocket Service
rabbitmq.exchange.new-messages=new-messages-exchange
# Exchange for broadcasting saved messages from Message Service
rabbitmq.exchange.saved-messages=saved-messages-exchange
# --- Queue Names ---
# Queue for the Message Service to consume new messages from
rabbitmq.queue.new-messages=q.new-messages
# Queue for the WebSocket Service to consume saved messages from
rabbitmq.queue.saved-messages-websocket=q.saved-messages.websocket
# --- Routing Keys ---
# Routing key used by WebSocket Service to PUBLISH new messages
rabbitmq.routing-key.new=message.new
# Routing key pattern used by WebSocket Service to SUBSCRIBE to saved messages
# The '#' is a wildcard that means "match everything"
rabbitmq.routing-key.subscribe-all=#
